// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlEXWT-2Y1SAEP46RNqloPGfc7ELkKKHQ',
    appId: '1:299432086695:web:66fa41c4b036e2bd129f82',
    messagingSenderId: '299432086695',
    projectId: 'tracktraillogin',
    authDomain: 'tracktraillogin.firebaseapp.com',
    storageBucket: 'tracktraillogin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMVvMtzVFVV305bvv16Td6TNBUC6EVfPA',
    appId: '1:299432086695:android:9d3f8fd9877e70c3129f82',
    messagingSenderId: '299432086695',
    projectId: 'tracktraillogin',
    storageBucket: 'tracktraillogin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD47By1r5AbmIjGfg2zxTp4L57TmCupNjA',
    appId: '1:299432086695:ios:a3618fc5f82cbf20129f82',
    messagingSenderId: '299432086695',
    projectId: 'tracktraillogin',
    storageBucket: 'tracktraillogin.firebasestorage.app',
    androidClientId: '299432086695-h5lshjo7kfdmj776cfih1ab072em9nqc.apps.googleusercontent.com',
    iosClientId: '299432086695-mn4jrvcnfgou452u04580roa9927ath2.apps.googleusercontent.com',
    iosBundleId: 'com.app.tracktrail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD47By1r5AbmIjGfg2zxTp4L57TmCupNjA',
    appId: '1:299432086695:ios:60d42610920d932d129f82',
    messagingSenderId: '299432086695',
    projectId: 'tracktraillogin',
    storageBucket: 'tracktraillogin.firebasestorage.app',
    androidClientId: '299432086695-h5lshjo7kfdmj776cfih1ab072em9nqc.apps.googleusercontent.com',
    iosClientId: '299432086695-453po6eeanki1bf9jllmvk62t3a1vkek.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlEXWT-2Y1SAEP46RNqloPGfc7ELkKKHQ',
    appId: '1:299432086695:web:4c66bd96eff8a958129f82',
    messagingSenderId: '299432086695',
    projectId: 'tracktraillogin',
    authDomain: 'tracktraillogin.firebaseapp.com',
    storageBucket: 'tracktraillogin.firebasestorage.app',
  );

}